language: java
jdk: openjdk8
env:
  global:
    - secure: STtOUYoLfzmXYOCGTCFsSXDsofwgqZE+mzbotCU0joPGAABucYIrwy4XNirMyOcCskYIN7H4MFXw9URwHulZNkYbDxbO9dXXAN4dkuvoZeCb3/1xOmsE3s1dnxzrtzfoRI3IYpE1ewW9uBMtSOgcgcc5Iu7vLPcfU035z89n8ld6I7KrYk6GGIp6R6B1Xgiu8DYsr8aG3/vXhUyrkG0Pn7lk6qbwWxeB0EK6EhNN/JyxPBwfEw3BlsPHoY6szENDmZWqYTbbYtaCnUKCzhjYbQgSXjCijwialVoX/+BqU6Q3gJEeD/nHhh+Qzh/+Os+J+yQyrISXKRB7v0+zy7c2CbKMcmoKL6oXEKnEdyIXoUE2GUZVDOSGVdvJA9xWP0ka06fmgzzduWvJ70u/9iPDr8JP0XdCtH24P1DAxMpVyjDtP6JPnVgHRd8PvpUlNrbp2iIYlz6pRKFzDZHahkm5E6YFZaRX1U20i8TYe2PyVTW05TkNdYvyVfNxkFkZkQerbn4Pgay2YydMCbvV5/Elz8mJO9xiSGJ5Pj8XTUEPCirNN2r9MbG2s4C8rIn5t8bBugg7WMgEly6I1mxyEeZAEGSYW51drb7wzxX8KSe8bnFiXI08aXpCPzc6mVAn/nOlPcLOu8lExuoXTPWFLLRSH0x+sQ8yAzB/+LQRur1PGe0=
    - secure: oDh1mGPkEyKaEU9H07UJ/78vY1rBG7gPMVbBz8IZr8JoLEya6UsZMwgnrw8NMbP4qa1u5eJ9/CPwfXI7bKVxGiTvMMojUabsdCX02+OnCkFgZSMzMqP3dUfHRAcb0ZMy2Aq1DHHvpfql8PxiaaMmO5t6Magw8eMUs2ASgz9EwTOPK2PPmZ5nGkXKy488ouSvgvmH/urUzTckuMD1Fv7PS/hbtfjoVafHOMcR+2Jmh+1mSofL702mQRacfRMiECVTFmuI5TLUdZwUHVcHqrn/5a55YE/B+S7mGL2j8SsZe2LUwMr0eMNmCg/zRoavB70k6267VB6Hd9RLQEXp3o7Uyly7EtIqG1OC60KhD5EsIwAMediBpUbQAkU0QSn0jL5rBpB2rS4GcT1foAfNaHJ4fSoSPNscBZxDFX6ASVb1x0Ld4/qi9OMqq4IRBcKWBdQht9ql4Wp3VW1qSj/7S/h7Kl1u9uUowrTzipuNCLisWhCTAPNM6pTAwbUqbFeyH8RUqUeqeYwWOd5d7bWQ9M+0rjJJ880HE1KaHdGUSFpqRq8obKSVlYJ2/XTXICIc5AwePDFZKDVBb2Hzg58E29fE0+uJx44oILs0dsvaCLfbyOCNQPNblPaJG/m/dr4nrx3Un415Un41+shtB35IYCo1Xil2iDYhqUg5Ocp4MkBgLF0=

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: script
  script: ./gradlew bintrayPublish
  skip_cleanup: true
  on:
    tags: true
